version: '3.8'
services:
  web:
    image: ruby:3.3.0
    command: bash -c "bundle install && bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/myapp
    working_dir: /myapp
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=sqlite3:/myapp/storage/development.sqlite3
    depends_on:
      - redis
  
  worker:
    image: ruby:3.3.0
    command: bash -c "bundle install && bundle exec sidekiq"
    volumes:
      - .:/myapp
    working_dir: /myapp
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=sqlite3:/myapp/storage/development.sqlite3
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
